name: appmarketplace
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1      # Última versión disponible
  firebase_auth: ^5.5.1       # Última versión disponible para autenticación
  cloud_firestore: ^5.6.5     # Última versión disponible para Firestore
  firebase_storage: ^12.4.4   # Última versión disponible para almacenamiento
  firebase_app_check: ^0.3.2+4
  google_sign_in: ^6.1.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0  # O la versión más reciente
  path_provider: ^2.0.14
  image: ^4.5.3
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder.png